#!/usr/bin/env python3
"""Generate today's actionable market brief from live candles. Foreground-safe."""
import json, os, sys, time
from datetime import datetime, timezone
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import feed, indicators as I

SYMBOLS = ["EURUSD","GBPUSD","USDJPY","AUDUSD","USDCAD","USDCHF","NZDUSD","EURJPY","GBPJPY","XAUUSD"]

def analyze(sym):
    try:
        cs = feed.candles(sym, interval="1h", rng="10d")
    except Exception as e:
        return {"symbol": sym, "error": repr(e)}
    if not cs or len(cs) < 60:
        return {"symbol": sym, "error": f"insufficient candles ({len(cs) if cs else 0})"}
    c = [x["c"] for x in cs]
    price = c[-1]
    ema21 = I.ema(c,21)[-1]; ema50 = I.ema(c,50)[-1]; ema200 = I.ema(c,200)[-1] if len(c)>=200 else None
    rsi = I.rsi(c,14)[-1]; atr = I.atr(cs,14)[-1]; adx = I.adx(cs,14)[-1]
    trend = "up" if (ema200 and price>ema50>ema200) else "down" if (ema200 and price<ema50<ema200) else "range"
    if rsi > 70: bias="overbought"
    elif rsi < 30: bias="oversold"
    else: bias="neutral"
    if adx is None or adx < 20: conv="low"
    elif adx < 25: conv="moderate"
    else: conv="trending"
    return {"symbol":sym,"price":round(price,5),"ema21":round(ema21,5),"ema50":round(ema50,5),
            "ema200":round(ema200,5) if ema200 else None,"rsi":round(rsi,1),"atr":round(atr,5),
            "adx":round(adx,1),"trend":trend,"bias":bias,"conviction":conv,
            "suggested_stop":round(price-1.5*atr,5) if trend=="up" else round(price+1.5*atr,5)}

rows=[analyze(s) for s in SYMBOLS]
now=datetime.now(timezone.utc)
out=[f"# Zpt Daily Market Brief — {now.strftime('%Y-%m-%d %H:%M UTC')}","",
     "Actionable FX/metals snapshot (1h). Risk: max 1-2%/trade, ALWAYS stop-loss.","",
     "| Symbol | Price | Trend | RSI | ADX | Conviction | Suggested Stop |",
     "|---|---|---|---|---|---|---|"]
for r in rows:
    if "error" in r: out.append(f"| {r['symbol']} | — | error: {r['error'][:40]} | | | | |")
    else: out.append(f"| {r['symbol']} | {r['price']} | {r['trend']}/{r['bias']} | {r['rsi']} | {r['adx']} | {r['conviction']} | {r['suggested_stop']} |")
out += ["","## Trade candidates (trend + conviction>=moderate + RSI not exhausted)"]
cands=[r for r in rows if "error" not in r and r["conviction"] in ("moderate","trending") and 35<r["rsi"]<65 and r["trend"]!="range"]
if not cands: out.append("- None today — stand aside (capital preservation > activity).")
for r in cands:
    out.append(f"- **{r['symbol']}**: {r['trend']} trend, RSI {r['rsi']}, ADX {r['adx']}. Stop {r['suggested_stop']}.")
out += ["", f"*Generated by ZptMaster autonomously. {sum('error' not in r for r in rows)}/{len(rows)} symbols live.*"]

os.makedirs("reports", exist_ok=True)
path=f"reports/brief_{now.strftime('%Y-%m-%d')}.md"
open(path,"w").write("\n".join(out))
open("reports/latest.md","w").write("\n".join(out))
print("\n".join(out))
